name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["23"]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build

    - name: Check spelling
      uses: crate-ci/typos@master

    - name: Check README is up-to-date
      run: |
        npm run readme
        git diff --exit-code
